// Default contract address configuration
// This can be overridden by environment variables
export const DEFAULT_ADDRESSES = {
  localnet: {
    muxAccount: "",
    muxAccountFactory: "",
    muxBatcher: "",
    muxDelegation: "",
    muxPermissions: "",
    muxPolicy: "",
    muxRecovery: "",
    muxRegistry: "",
    muxSpendingPolicy: "",
    muxWalletRegistry: "",
  },
  testnet: {
    muxAccount: "",
    muxAccountFactory: "",
    muxBatcher: "",
    muxDelegation: "",
    muxPermissions: "",
    muxPolicy: "",
    muxRecovery: "",
    muxRegistry: "",
    muxSpendingPolicy: "",
    muxWalletRegistry: "",
  },
  mainnet: {
    muxAccount: "",
    muxAccountFactory: "",
    muxBatcher: "",
    muxDelegation: "",
    muxPermissions: "",
    muxPolicy: "",
    muxRecovery: "",
    muxRegistry: "",
    muxSpendingPolicy: "",
    muxWalletRegistry: "",
  },
};
